version: '2'

volumes:
  cert_dir:
    driver: local
  node_modules:
    driver: local
  rails_vendor:
    driver: local

services:
  stock_api_mocksmtp:
    extends:
      file: docker-compose-base.yml
      service: stock_api_mocksmtp

  stock_api_rails:
    extends:
      file: docker-compose-base.yml
      service: stock_api_rails
    volumes:
      - rails_vendor:${RAILS_APP_MOUNT_TO}/vendor
      - node_modules:${RAILS_APP_MOUNT_TO}/node_modules
    depends_on:
      - stock_api_mocksmtp

  stock_api_revproxy:
    extends:
      file: docker-compose-base.yml
      service: stock_api_revproxy
    volumes:
      - cert_dir:/etc/letsencrypt
    depends_on:
      - stock_api_rails

