eval_gemfile 'Gemfile.default'

group :development, :test do
  # for debugging
  gem 'pry', '~> 0.13.1'
  gem 'pry-rails'    # rails cの対話式コンソールがirbの代わりにリッチなpryになる
  gem 'pry-doc', '~> 1.1.0' # pry中に show-source [method名] でソース内を読める
  gem 'pry-stack_explorer', '~> 0.5.1'   # pry中にスタックを上がったり下がったり行き来できる
  gem 'pry-byebug'   # binding.pryをソースに記載すると、ブレイクポイントとなりデバッグが可能になる
  gem 'hirb'         # モデルの出力結果を表形式で表示するGem
  gem 'hirb-unicode' # 日本語などマルチバイト文字の出力時の出力結果のずれに対応
end
